In [ ]:
#1
import numpy as np
import pandas as pd

arr = np.arange(1,9,1)
arr = arr.reshape(4,2)
arr.astype('i')

arr.dtype

dtype('int64')

In [ ]:

#2
a = np.arange(100,200,10)
a = a.reshape(5,2)
a

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [ ]:

#3
sarr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
s =sarr[sarr[:,1].argsort()[::-1]]

print(s)

[[77 88 99]
 [44 55 66]
 [11 22 33]]


In [ ]:
#4
sarray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

for i in range(0,6):
    for j in range(0,4):
        if i%2 == 1 and j%2 == 0:
           print(sarray[i][j])


15
21
39
45


IndexError: ignored

In [ ]:
#5
arr1 = np.array([[5, 6, 9], [21 ,18, 27]])
arr2 = np.array([[15 ,33, 24], [4 ,7, 1]])
arr = np.concatenate((arr1, arr2))

arr = np.square(arr, out=None, where=True, dtype=None)

print(arr)

[[  25   36   81]
 [ 441  324  729]
 [ 225 1089  576]
 [  16   49    1]]


In [ ]:
#6

df = pd.read_csv('ds_salaries.csv')
df.replace('?','0')
df.replace('NaN','0')
df.replace('n.a','0')


df

Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Data Engineer   85000             GBP         109024   
3          Product Data Analyst   20000             USD          20000   
4     Machine Learning Engineer  150000             USD         150000   
..                          ...     ...             ...            ...   
602               Data Engineer  154000             USD         154000   
603               Data Engineer  126000             USD         126000   
604                Data Analyst  129000             USD         129000   
605                Data Analyst  150000             USD         150000   
606                AI Scientist  200000             USD         200000   

    employee_residence  remote_ratio company_location company_size  
0                   DE             0               DE            L  
1                   JP             0               JP            S  
2                   GB            50               GB            M  
3                   HN             0               HN            S  
4                   US            50               US            L  
..                 ...           ...              ...          ...  
602                 US           100               US            M  
603                 US           100               US            M  
604                 US             0               US            M  
605                 US           100               US            M  
606                 IN           100               US            L  

[607 rows x 12 columns]

In [ ]:
#7
salary = df.sort_values(by = ['salary_in_usd'],  ascending=False)
salary

Unnamed: 0  work_year experience_level employment_type  \
252         252       2021               EX              FT   
97           97       2021               MI              FT   
33           33       2020               MI              FT   
157         157       2021               MI              FT   
225         225       2021               EX              CT   
..          ...        ...              ...             ...   
179         179       2021               MI              FT   
77           77       2021               MI              PT   
238         238       2021               EN              FT   
185         185       2021               MI              FT   
176         176       2021               MI              FT   

                              job_title  salary salary_currency  \
252             Principal Data Engineer  600000             USD   
97               Financial Data Analyst  450000             USD   
33                   Research Scientist  450000             USD   
157  Applied Machine Learning Scientist  423000             USD   
225            Principal Data Scientist  416000             USD   
..                                  ...     ...             ...   
179                      Data Scientist  420000             INR   
77        3D Computer Vision Researcher  400000             INR   
238                      Data Scientist    4000             USD   
185                       Data Engineer    4000             USD   
176                      Data Scientist   58000             MXN   

     salary_in_usd employee_residence  remote_ratio company_location  \
252         600000                 US           100               US   
97          450000                 US           100               US   
33          450000                 US             0               US   
157         423000                 US            50               US   
225         416000                 US           100               US   
..             ...                ...           ...              ...   
179           5679                 IN           100               US   
77            5409                 IN            50               IN   
238           4000                 VN             0               VN   
185           4000                 IR           100               IR   
176           2859                 MX             0               MX   

    company_size  
252            L  
97             L  
33             M  
157            L  
225            S  
..           ...  
179            S  
77             M  
238            M  
185            M  
176            S  

[607 rows x 12 columns]

In [ ]:
max(df["salary_in_usd"])

600000

In [ ]:
#8
df.loc[1]



Unnamed: 0                                     1
work_year                                   2020
experience_level                              SE
employment_type                               FT
job_title             Machine Learning Scientist
salary                                    260000
salary_currency                              USD
salary_in_usd                             260000
employee_residence                            JP
remote_ratio                                   0
company_location                              JP
company_size                                   S
Name: 1, dtype: object

In [ ]:
#9

df['salary'].value_counts()



100000     18
80000      18
120000     15
60000      15
150000     14
           ..
256000      1
39600       1
1335000     1
52500       1
129000      1
Name: salary, Length: 272, dtype: int64

In [ ]:
#11

df["job_title"].value_counts()

Data Scientist                              143
Data Engineer                               132
Data Analyst                                 97
Machine Learning Engineer                    41
Research Scientist                           16
Data Science Manager                         12
Data Architect                               11
Big Data Engineer                             8
Machine Learning Scientist                    8
Principal Data Scientist                      7
AI Scientist                                  7
Data Science Consultant                       7
Director of Data Science                      7
Data Analytics Manager                        7
ML Engineer                                   6
Computer Vision Engineer                      6
BI Data Analyst                               6
Lead Data Engineer                            6
Data Engineering Manager                      5
Business Data Analyst                         5
Head of Data                            