In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv('F:\ds_salaries.csv')


In [24]:
#pandas
#1
df.describe()

Unnamed: 0    work_year        salary  salary_in_usd  remote_ratio
count  607.000000   607.000000  6.070000e+02     607.000000     607.00000
mean   303.000000  2021.405272  3.240001e+05  112297.869852      70.92257
std    175.370085     0.692133  1.544357e+06   70957.259411      40.70913
min      0.000000  2020.000000  4.000000e+03    2859.000000       0.00000
25%    151.500000  2021.000000  7.000000e+04   62726.000000      50.00000
50%    303.000000  2022.000000  1.150000e+05  101570.000000     100.00000
75%    454.500000  2022.000000  1.650000e+05  150000.000000     100.00000
max    606.000000  2022.000000  3.040000e+07  600000.000000     100.00000

In [14]:
#2
df_new = df["salary"].sort_values()
df_new

238        4000
185        4000
15         8000
124        8760
196        9272
         ...   
285     7000000
137     8500000
7      11000000
102    11000000
177    30400000
Name: salary, Length: 607, dtype: int64

In [61]:
#3
dic1 = {
    "name" : ["mahmoud","ali","mohammed"],
    "age" : [21,24,19]
}

dic2 = {
    "grade":[89,75,56]
}

df1 = pd.DataFrame(dic1)
df2 = pd.DataFrame(dic2)

df1.join(df2)

name  age  grade
0   mahmoud   21     89
1       ali   24     75
2  mohammed   19     56

In [48]:
#numpy
#1
arr = np.array([[10,11,12,13,14,15,16,17],[18,19,20,21,22,23,24,25],[26,27,28,29,30,31,32,33]])
arr = arr.reshape(4,6)
arr

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

In [154]:
#2
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
x = np.copy(sampleArray[1])
y = np.copy(sampleArray[0])
sampleArray[1] = y
sampleArray[0] = x
sampleArray


array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])

In [142]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
np.sort(sampleArray,1)

array([[34, 43, 73],
       [12, 22, 82],
       [53, 66, 94]])

In [94]:
#3
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
print(min(sampleArray[0]))
print(max(sampleArray[1]))

34
82


In [134]:
#4
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])
np.delete(sampleArray ,1,1)

array([[34, 73],
       [82, 12],
       [53, 66]])